

name: Polyel Docs CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Trigger Polyel Docs update & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the Polyel Docs Ci process
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: Polyel-Docs-Ci
          owner: Superbition
          event_type: deploy_push
